import Head from 'next/head'
import Navbar from './Navbar'
import Footer from './Footer'

const layout = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Pattraco</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className="w-full scroll-smooth h-full min-h-screen">
        <Navbar />
        <div className="w-full">{children}</div>
        <Footer />
      </div>
    </div>
  )
}

export default layout
