import { faEnvelope, faPhone } from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { motion } from 'framer-motion'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import PaddingLayout from '../components/PaddingLayout'
import ContactSVG from '../public/blogging.svg'
import { fadeIn } from '../utils/animation-variants'

const Saibarrelco = () => {
  const [sections, setSections] = useState(null)
  const [isLoading, setLoading] = useState(false)

  useEffect(() => {
    setLoading(true)
    fetch('api/saibarrelco')
      .then((res) => res.json())
      .then((data) => {
        setSections(data.sections)
        setLoading(false)
      })
  }, [])

  return (
    <motion.div exit={{ opacity: 0 }}>
      <Head>
        <title>Contact - Pattraco</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className="h-full md:main-height-without-footer bg-primary w-full">
        <div className="flex flex-col md:flex-row items-center md:space-x-10 md:py-10 md:px-24 px-2 py-4">
          <div className="w-1/2 hidden md:block">
            <ContactSVG />
          </div>

          <div className="w-full md:w-1/2 bg-white shadow rounded p-6 mx-auto">
            <motion.div initial="hidden" animate="visible" variants={fadeIn}>
              <div className="text-4xl pb-1 mb-2 font-semibold">Contact Us</div>
              <div className="flex flex-col md:flex-row md:space-x-6 mb-6">
                <div>
                  <a href="mailto:info@pattrco.com">
                    <FontAwesomeIcon icon={faEnvelope} className="mr-2" />
                    <span>info@pattraco.com</span>
                  </a>
                </div>
                <div>
                  <a href="tel:+919915381868">
                    <FontAwesomeIcon icon={faPhone} className="mr-2" />
                    +91-9915381868
                  </a>
                </div>
              </div>
              <div className="flex flex-col mb-2">
                <label htmlFor="name">Full Name</label>
                <input
                  type="text"
                  name="name"
                  className="border border-primary px-2 py-4 bg-white rounded w-full "
                  id="name"
                  placeholder="John Doe"
                />
              </div>
              <div className="flex flex-col mb-2">
                <label htmlFor="email">Email</label>
                <input
                  type="email"
                  name="email"
                  className="border border-primary px-2 py-4 bg-white rounded w-full "
                  id="email"
                  placeholder="johndoe@gmail.com"
                />
              </div>
              <div className="flex flex-col mb-2">
                <label htmlFor="phone">Phone</label>
                <input
                  type="text"
                  name="phone"
                  className="border border-primary px-2 py-4 bg-white rounded w-full "
                  id="phone"
                  placeholder="+91-XXXXXXXXXX"
                />
              </div>
              <div className="flex flex-col mb-4">
                <label htmlFor="message" className="text-sm">
                  Message
                </label>
                <textarea
                  name="message"
                  className="border border-primary px-2 py-4 bg-white rounded w-full "
                  id="phone"
                  placeholder="Your message here..."
                />
              </div>
              <div>
                <button className="text-white bg-primary text-xl font-normal uppercase w-full  px-2 py-4 rounded hover:bg-black/70 transition">
                  Send Message
                </button>
              </div>
            </motion.div>
          </div>
        </div>
        <PaddingLayout />
      </main>
    </motion.div>
  )
}

export default Saibarrelco
