import { faEnvelope, faPhone } from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { motion } from 'framer-motion'
import Head from 'next/head'
import PaddingLayout from '../components/PaddingLayout'
import ContactSVG from '../public/blogging.svg'
import { fadeIn } from '../utils/animation-variants'
import { useState, useRef } from 'react'

const Contact = () => {
  const formEl = useRef(null)
  const [loading, setLoading] = useState(false)
  const [success, setSuccess] = useState(false)
  const [status, setStatus] = useState('')
  const CAPTCHA_KEY = '6Lf5uCYgAAAAAG2AvNTqEpmIEmpF8ohpyC8T8WR9'

  const handleSubmit = async (e) => {
    e.preventDefault()

    setLoading(true)
    const data = new FormData(e.currentTarget)
    const response = await fetch(e.currentTarget.action, {
      method: 'POST',
      body: data,
      headers: {
        Accept: 'application/json',
      },
    })

    if (response.status === 200) {
      setLoading(false)
      setSuccess(true)
      setStatus("Thank you for contacting. We'll get in touch with you soon!")
      if (formEl && formEl.current) {
        formEl.current.reset()
      }
    } else {
      setLoading(false)
      setSuccess(false)
      setStatus('Oops! There was a problem submitting your form')
    }
  }

  return (
    <motion.div exit={{ opacity: 0 }}>
      <Head>
        <title>Contact - Pattraco</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className="h-full lg:min-h-screen lg:h-full bg-primary w-full">
        <div className="flex flex-col lg:flex-row items-center lg:space-x-10 lg:py-10 lg:px-24 px-2 py-4">
          <div className="w-1/2 hidden lg:block">
            <ContactSVG />
          </div>

          <div className="w-full lg:w-1/2 bg-white shadow rounded-2xl p-6 mx-auto">
            <motion.div initial="hidden" animate="visible" variants={fadeIn}>
              <div className="text-4xl pb-1 mb-2 font-semibold">Contact Us</div>
              <div className="flex flex-col lg:flex-row lg:space-x-6 mb-6">
                <div>
                  <a href="mailto:info@pattrco.com">
                    <FontAwesomeIcon icon={faEnvelope} className="mr-2" />
                    <span>info@pattraco.com</span>
                  </a>
                </div>
                <div>
                  <a href="tel:+919915381868">
                    <FontAwesomeIcon icon={faPhone} className="mr-2" />
                    +91-9915381868
                  </a>
                </div>
              </div>
              <form
                ref={formEl}
                onSubmit={handleSubmit}
                id="contact-form"
                action="https://formspree.io/f/xgeddljg"
                method="POST"
              >
                <div className="flex flex-col mb-2">
                  <label htmlFor="name">Full Name</label>
                  <input
                    type="text"
                    name="name"
                    className="border border-primary px-2 py-4 bg-white rounded w-full "
                    id="name"
                    placeholder="John Doe"
                  />
                </div>
                <div className="flex flex-col mb-2">
                  <label htmlFor="email">Email</label>
                  <input
                    type="email"
                    name="email"
                    className="border border-primary px-2 py-4 bg-white rounded w-full "
                    id="email"
                    placeholder="johndoe@gmail.com"
                  />
                </div>
                <div className="flex flex-col mb-2">
                  <label htmlFor="phone">Phone</label>
                  <input
                    type="text"
                    name="phone"
                    className="border border-primary px-2 py-4 bg-white rounded w-full "
                    id="phone"
                    placeholder="+91-XXXXXXXXXX"
                  />
                </div>
                <div className="flex flex-col mb-4">
                  <label htmlFor="message" className="text-sm">
                    Message
                  </label>
                  <textarea
                    name="message"
                    className="border border-primary px-2 py-4 bg-white rounded w-full "
                    id="phone"
                    placeholder="Your message here..."
                  />
                </div>
                <div className="form-control flex flex-col py-4">
                  <div className="g-recaptcha" data-sitekey={CAPTCHA_KEY}></div>
                </div>
                <div>
                  <button
                    disabled={loading}
                    className="text-white bg-primary text-xl font-normal uppercase w-full  px-2 py-4 rounded hover:bg-black/70 transition disabled:opacity-50"
                  >
                    {loading ? 'Submitting...' : 'Submit'}
                  </button>
                </div>
                {status ? (
                  <div
                    className={`${
                      success ? 'bg-green' : 'bg-red'
                    } w-full my-4 rounded py-2 px-2 text-white`}
                  >
                    {status}
                  </div>
                ) : null}
              </form>
            </motion.div>
          </div>
        </div>
        <PaddingLayout />
      </main>
    </motion.div>
  )
}

export default Contact
