import Head from 'next/head'
import { useEffect, useState } from 'react'
import ContentSectionCard from '../components/ContentSectionCard'
import HeroSection from '../components/HeroSection'
import PaddingLayout from '../components/PaddingLayout'
import fmcgBg from '../public/fmcg.webp'

const ImperialStores = () => {
  const [sections, setSections] = useState(null)
  const [isLoading, setLoading] = useState(false)

  useEffect(() => {
    setLoading(true)
    fetch('api/imperial-stores')
      .then((res) => res.json())
      .then((data) => {
        setSections(data.sections)
        setLoading(false)
      })
  }, [])

  return (
    <div>
      <Head>
        <title>Imperial Stores - Pattraco</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className="bg-gray-100">
        <HeroSection
          imageSrc={fmcgBg}
          mainTitle="Imperial Stores"
          subTitle="FMCG Retail"
        />
        <div className="py-6 md:py-10 bg-white flex justify-center flex-col">
          <div className="container mx-auto bg-white text-xl md:text-2xl font-normal md:text-center px-2 md:px-0">
            The buzzing new era of DIY - hygiene-conscious food, we bring
            Imperial Stores to multiple cities of India.
          </div>
          <div className="max-w-3xl self-center text-base md:text-lg md:text-center mt-4 px-2 md:px-0">
            With our growing presence in Chandigarh, Gurgaon, New Delhi,
            Patiala, Amritsar, Jaipur, and many more cities, we create the most
            efficient, organized and hygienic shopping experiences for our
            customers.
          </div>
        </div>
        <div className="flex justify-center">
          <div className="grid grid-cols-1 pt-10 w-full max-w-5xl">
            {!isLoading &&
              sections &&
              sections.map((section) => (
                <ContentSectionCard
                  key={section.id}
                  mainTitle={section.mainTitle}
                  content={section.content}
                />
              ))}
          </div>
        </div>
        <PaddingLayout />
      </main>
    </div>
  )
}

export default ImperialStores
