import { motion } from 'framer-motion'
import Head from 'next/head'
import ContentSectionGrid from '../components/ContentSectionGrid'
import HeroSection from '../components/HeroSection'
import PaddingLayout from '../components/PaddingLayout'
import fmcgImageOne from '../public/fmcg/fmcg-image-1.webp'
import fmcgImageTwo from '../public/fmcg/fmcg-image-2.webp'
import fmcgImageThree from '../public/fmcg/fmcg-image-3.webp'
import { fadeIn } from '../utils/animation-variants'

const sections = [
  {
    id: 1,
    imageSrc: fmcgImageTwo,
    mainTitle: 'Health Food Innovatives',
    content:
      'Our partnership with leading Indian brands, that manufacture healthy, preservative free foods - is loved by our customers. The promise of health is delivered at Imperial Stores.',
  },
  {
    id: 2,
    imageSrc: fmcgImageThree,
    mainTitle: 'Cost Effective Luxury',
    content:
      'Fast moving consumer goods - are closely connected to your health. And we understand the value of your safety. This encourages us to create the most effective, supply chain - which is not only affordable - but also promises the luxury your body deserves.',
  },
]

const ImperialStores = () => {
  return (
    <motion.div exit={{ opacity: 0 }}>
      <Head>
        <title>Imperial Stores - Pattraco</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className="bg-primary-background">
        <HeroSection
          imageSrc={fmcgImageOne}
          mainTitle="Imperial Stores"
          subTitle="FMCG Retail"
        />
        <div className="py-6 lg:py-10 bg-primary text-primary-background flex justify-center flex-col">
          <motion.div
            initial="hidden"
            viewport={{ once: true }}
            whileInView="visible"
            variants={fadeIn}
          >
            <div className="container mx-auto text-xl lg:text-4xl font-medium lg:text-center px-2 lg:px-2 xl:px-0">
              The buzzing new era of DIY - hygiene-conscious food, we bring
              Imperial Stores to multiple cities of India.
            </div>
          </motion.div>
          <motion.div
            initial="hidden"
            viewport={{ once: true }}
            whileInView="visible"
            variants={fadeIn}
          >
            <div className="max-w-3xl flex justify-center mx-auto self-center text-base lg:text-lg lg:text-center mt-4 px-2 lg:px-2 xl:px-0">
              With our growing presence in Chandigarh, Gurgaon, New Delhi,
              Patiala, Amritsar, Jaipur, and many more cities, we create the
              most efficient, organized and hygienic shopping experiences for
              our customers.
            </div>
          </motion.div>
        </div>
        <div className="flex justify-center">
          <ContentSectionGrid sections={sections} />
        </div>
        <PaddingLayout />
      </main>
    </motion.div>
  )
}

export default ImperialStores
