import Head from 'next/head'
import Link from 'next/link'
import { useState } from 'react'

export default function Home() {
  const [currentBg, setCurrentBg] = useState('')
  return (
    <div className={`${currentBg} bg-cover bg-opacity-80 font-sans text-black`}>
      <Head>
        <title>Pattraco</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full">
        <div className="container mx-auto">
          <div className="flex h-full pt-24 justify-center flex-col">
            <div className="px-16">
              <div className="text-5xl font-extralight py-2">
                <Link href="/">
                  <>
                    Solar - <span className="font-normal">Sun Infinity</span>
                  </>
                </Link>
              </div>
              <div className="text-5xl font-extralight py-2">
                <Link href="/">
                  <>
                    Earth-Mined Goodness -{' '}
                    <span className="font-normal">ZAYAA</span>
                  </>
                </Link>
              </div>
              <div className="text-5xl font-extralight py-2">
                <Link href="/">
                  <>
                    FMCG Retail -{' '}
                    <span className="font-normal">Imperial Stores</span>
                  </>
                </Link>
              </div>
              <div className="text-5xl font-extralight py-2">
                <Link href="/">
                  <>
                    Agro Technology -{' '}
                    <span className="font-normal">SAIBARRELCO</span>
                  </>
                </Link>
              </div>
              <div className="text-5xl font-extralight py-2">
                <Link href="/">
                  <>
                    CSR - <span className="font-normal">Your Soul Tribe</span>
                  </>
                </Link>
              </div>
              <div className="text-5xl font-extralight py-2">
                <Link href="/">Contact</Link>
              </div>
            </div>
          </div>
        </div>

        {/* <HomeCard title="Solar - Sun Infinity" imageSrc={SolarImage} />
        <HomeCard title="Earth-Mined Goodness - ZAYAA" imageSrc={MiningImage} />
        <HomeCard title="FMCG Retail - Imperial Stores" imageSrc={FMCGImage} />
        <HomeCard title="Agro Technology - SAIBARRELCO" imageSrc={AgroImage} /> */}
      </main>
    </div>
  )
}
