import Head from 'next/head'
import Link from 'next/link'
import HomeSlide from '../components/HomeSlide'
import HomeCard from '../components/HomeCard'
import agroBg from '../public/agro.webp'
import csrBg from '../public/csr.webp'
import fmcgBg from '../public/fmcg.webp'
import miningBg from '../public/mining.webp'
import solarBg from '../public/solar-panel.webp'

export default function Home() {
  const data = [
    {
      id: 1,
      href: '/sun-infinity',
      imageSrc: solarBg,
      mainTitle: 'Sun Infinity',
      subTitle: 'Solar',
    },
    {
      id: 2,
      href: '/zayaa',
      imageSrc: miningBg,
      mainTitle: 'ZAYAA',
      subTitle: 'Earth-Mined Goodness',
    },
    {
      id: 3,
      href: '/imperial-stones',
      imageSrc: fmcgBg,
      mainTitle: 'Imperial Stones',
      subTitle: 'FMCG Retail',
    },
    {
      id: 4,
      href: '/saibarrelco',
      imageSrc: agroBg,
      mainTitle: 'SAIBARRELCO',
      subTitle: 'Agro Technology',
    },
    {
      id: 5,
      href: '/yoru-soul-tribe',
      imageSrc: csrBg,
      mainTitle: 'Your Soul Tribe',
      subTitle: 'CSR',
    },
  ]

  return (
    <div className="font-sans container mx-auto text-black px-2 md:px-0">
      <Head>
        <title>Pattraco</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full main-height py-6">
        <div className="gap-4 h-full grid grid-cols-1 md:grid-cols-3 pb-2">
          {data.map(({ id, href, mainTitle, imageSrc, subTitle }) => (
            <Link key={id} href={href} passHref className="cursor-pointer">
              <HomeCard
                imageSrc={imageSrc}
                mainTitle={mainTitle}
                subTitle={subTitle}
              />
            </Link>
          ))}
        </div>
        <div className="flex justify-center self-center">Pattraco. 2022</div>
      </main>
    </div>
  )
}
