import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import HomeCard from '../components/HomeCard'
import useHover from '../hooks/useHover'
import agroBg from '../public/agro.webp'
import csrBg from '../public/csr.webp'
import fmcgBg from '../public/fmcg.webp'
import miningBg from '../public/mining.webp'
import solarBg from '../public/solar-panel.webp'
import mainBg from '../public/main.webp'

export default function Home() {
  const [agroHoverRef, isAgroHover] = useHover()
  const [miningHoverRef, isMiningHover] = useHover()
  const [fmcgHoverRef, isFmcgHover] = useHover()
  const [solarHoverRef, isSolarHover] = useHover()
  const [csrHoverRef, isCsrHover] = useHover()
  const [backgroundImage, setBackgroundImage] = useState('bg-white')

  useEffect(() => {
    if (isAgroHover) {
      setBackgroundImage('bg-agro')
    } else {
      setBackgroundImage('bg-white')
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isAgroHover])

  useEffect(() => {
    if (isMiningHover) {
      setBackgroundImage('bg-mining')
    } else {
      setBackgroundImage('bg-white')
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isMiningHover])

  useEffect(() => {
    if (isSolarHover) {
      setBackgroundImage('bg-solar')
    } else {
      setBackgroundImage('bg-white')
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isSolarHover])

  useEffect(() => {
    if (isFmcgHover) {
      setBackgroundImage('bg-fmcg')
    } else {
      setBackgroundImage('bg-white')
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isFmcgHover])

  useEffect(() => {
    if (isCsrHover) {
      setBackgroundImage('bg-csr')
    } else {
      setBackgroundImage('bg-white')
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isCsrHover])

  return (
    <div className="font-sans text-black">
      <Head>
        <title>Pattraco</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full">
        {/* Background */}
        <div className="hidden md:block w-full absolute left-0 top-0 bottom-0 overflow-hidden">
          <div className="w-full bg-gradient-to-r from-white/90 to-green-600/30 z-20 absolute left-0 top-0 bg-cover min-w-full h-full min-h-screen"></div>
          <div
            className={`${
              backgroundImage === 'bg-agro'
                ? 'opacity-100 scale-105'
                : 'opacity-0'
            } w-full transition-all ease-linear duration-500 z-10 absolute left-0 top-0 bg-cover min-w-full h-full min-h-screen`}
          >
            <Image src={agroBg} layout="fill" objectFit="cover" alt="Agro" />
          </div>
          <div
            className={`${
              backgroundImage === 'bg-mining'
                ? 'opacity-100 scale-105'
                : 'opacity-0'
            } w-full transition-all ease-linear duration-500 z-10 absolute left-0 top-0 bg-cover min-w-full h-full min-h-screen`}
          >
            <Image src={miningBg} layout="fill" objectFit="cover" alt="Agro" />
          </div>
          <div
            className={`${
              backgroundImage === 'bg-solar'
                ? 'opacity-100 scale-105'
                : 'opacity-0'
            } w-full transition-all ease-linear duration-500 z-10 absolute left-0 top-0 bg-cover min-w-full h-full min-h-screen`}
          >
            <Image src={solarBg} layout="fill" objectFit="cover" alt="Agro" />
          </div>
          <div
            className={`${
              backgroundImage === 'bg-fmcg'
                ? 'opacity-100 scale-105'
                : 'opacity-0'
            } w-full transition-all ease-linear duration-500 z-10 absolute left-0 top-0 bg-cover min-w-full h-full min-h-screen`}
          >
            <Image src={fmcgBg} layout="fill" objectFit="cover" alt="Agro" />
          </div>
          <div
            className={`${
              backgroundImage === 'bg-csr'
                ? 'opacity-100 scale-105'
                : 'opacity-0'
            } w-full transition-all ease-linear duration-500 z-10 absolute left-0 top-0 bg-cover min-w-full h-full min-h-screen`}
          >
            <Image src={csrBg} layout="fill" objectFit="cover" alt="Agro" />
          </div>
          <div
            className={`${
              backgroundImage === 'bg-white' ? 'opacity-100' : 'opacity-0'
            } w-full transition-all ease-linear duration-500 z-10 absolute left-0 top-0 bg-cover min-w-full h-full min-h-screen`}
          >
            <Image src={mainBg} layout="fill" objectFit="cover" alt="Agro" />
          </div>
        </div>
        {/* Web Layout */}
        <div className="hidden md:block relative container mx-auto z-40">
          <div className="h-full pt-24 justify-center flex-col inline-flex">
            <div className="px-4 md:px-16">
              <div
                ref={solarHoverRef}
                className="text-xl md:text-5xl cursor-pointer font-extralight py-2 md:py-4"
              >
                <Link href="/">
                  <>
                    Solar - <span className="font-normal">Sun Infinity</span>
                  </>
                </Link>
              </div>
              <div
                ref={miningHoverRef}
                className="text-xl md:text-5xl cursor-pointer font-extralight py-2 md:py-4"
              >
                <Link href="/">
                  <>
                    Earth-Mined Goodness -{' '}
                    <span className="font-normal">ZAYAA</span>
                  </>
                </Link>
              </div>
              <div
                ref={fmcgHoverRef}
                className="text-xl md:text-5xl cursor-pointer font-extralight py-2 md:py-4"
              >
                <Link href="/">
                  <>
                    FMCG Retail -{' '}
                    <span className="font-normal">Imperial Stores</span>
                  </>
                </Link>
              </div>
              <div
                ref={agroHoverRef}
                className="text-xl md:text-5xl cursor-pointer font-extralight py-2 md:py-4"
              >
                <Link href="/">
                  <>
                    Agro Technology -{' '}
                    <span className="font-normal">SAIBARRELCO</span>
                  </>
                </Link>
              </div>
              <div
                ref={csrHoverRef}
                className="text-xl md:text-5xl cursor-pointer font-extralight py-2 md:py-4"
              >
                <Link href="/">
                  <>
                    CSR - <span className="font-normal">Your Soul Tribe</span>
                  </>
                </Link>
              </div>
              <div className="text-xl md:text-5xl cursor-pointer font-extralight py-2 md:py-4">
                <Link href="/">Contact</Link>
              </div>
            </div>
          </div>
        </div>
        {/* Mobile Layout */}
        <div className="md:hidden w-full h-full min-h-screen py-10">
          <div className="container mx-auto px-4">
            <div className="font-sans py-4 mb-4 text-center uppercase font-light text-2xl border-black border">
              Explore
            </div>
            <div className="flex flex-col space-y-4">
              <Link
                href="/sun-infinity"
                passHref
                className="cursor-pointer my-4"
              >
                <HomeCard
                  imageSrc={fmcgBg}
                  mainTitle="Sun Infinity"
                  subTitle="Solar"
                />
              </Link>
              <Link href="/zayaa" passHref className="cursor-pointer my-4">
                <HomeCard
                  imageSrc={miningBg}
                  mainTitle="ZAYAA"
                  subTitle="Earth-Mined Goodness"
                />
              </Link>
              <Link href="/contact" passHref className="cursor-pointer my-4">
                <HomeCard
                  imageSrc={fmcgBg}
                  mainTitle="Imperial Stones"
                  subTitle="FMCG Retail"
                />
              </Link>
              <Link href="/contact" passHref className="cursor-pointer my-4">
                <HomeCard
                  imageSrc={agroBg}
                  mainTitle="SAIBARRELCO"
                  subTitle="Agro Technology"
                />
              </Link>
              <Link href="/contact" passHref className="cursor-pointer my-4">
                <HomeCard
                  imageSrc={csrBg}
                  mainTitle="Your Soul Tribe"
                  subTitle="CSR"
                />
              </Link>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}
