import Head from 'next/head'
import HomeCard from '../components/HomeCard'
import SolarImage from '../public/solar-panel.jpeg'
import MiningImage from '../public/mining.jpeg'
import FMCGImage from '../public/fmcg.jpeg'

export default function Home() {
  return (
    <div className="font-sans font-bold text-3xl text-black">
      <Head>
        <title>Pattraco</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full">
        <HomeCard title="Solar - Sun Infinity" imageSrc={SolarImage} />
        <HomeCard title="Earth-Mined Goodness - ZAYAA" imageSrc={MiningImage} />
        <HomeCard title="FMCG Retail - Imperial Stores" imageSrc={FMCGImage} />
      </main>
    </div>
  )
}
