import Head from 'next/head'
import { useEffect, useState } from 'react'
import ContentSectionCard from '../components/ContentSectionCard'
import HeroSection from '../components/HeroSection'
import PaddingLayout from '../components/PaddingLayout'
import agroBg from '../public/agro.webp'

const Saibarrelco = () => {
  const [sections, setSections] = useState(null)
  const [isLoading, setLoading] = useState(false)

  useEffect(() => {
    setLoading(true)
    fetch('api/saibarrelco')
      .then((res) => res.json())
      .then((data) => {
        setSections(data.sections)
        setLoading(false)
      })
  }, [])

  return (
    <div>
      <Head>
        <title>Saibarrelco - Pattraco</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className="bg-gray-100">
        <HeroSection
          imageSrc={agroBg}
          mainTitle="Saibarrelco"
          subTitle="Agro Technology"
        />
        <div className="flex justify-center">
          <div className="grid grid-cols-1 pt-4 md:pt-10 w-full max-w-5xl">
            {!isLoading &&
              sections &&
              sections.map((section) => (
                <ContentSectionCard
                  key={section.id}
                  mainTitle={section.mainTitle}
                  content={section.content}
                />
              ))}
          </div>
        </div>
        <PaddingLayout />
      </main>
    </div>
  )
}

export default Saibarrelco
