import Head from 'next/head'
import { useEffect, useState } from 'react'
import ContentSection from '../components/ContentSection'
import ContentSectionCard from '../components/ContentSectionCard'
import HeroSection from '../components/HeroSection'
import PaddingLayout from '../components/PaddingLayout'
import solarBg from '../public/solar-panel.webp'

const SunInfinity = () => {
  const [sections, setSections] = useState(null)
  const [isLoading, setLoading] = useState(false)

  useEffect(() => {
    setLoading(true)
    fetch('api/sun-infinity')
      .then((res) => res.json())
      .then((data) => {
        setSections(data.sections)
        setLoading(false)
      })
  }, [])

  return (
    <div>
      <Head>
        <title>Sun Infinity - Pattraco</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className="bg-gray-100">
        <HeroSection
          imageSrc={solarBg}
          mainTitle="Sun Infinity"
          subTitle="Solar"
        />
        <div className="flex justify-center">
          <div className="grid grid-cols-1 pt-10 w-full max-w-5xl">
            {!isLoading &&
              sections &&
              sections.map((section) => (
                <ContentSectionCard
                  key={section.id}
                  mainTitle={section.mainTitle}
                  content={section.content}
                />
              ))}
          </div>
        </div>
        <PaddingLayout />
      </main>
    </div>
  )
}

export default SunInfinity
