import { useState, useEffect } from 'react'
import Head from 'next/head'
import solarBg from '../public/solar-panel.webp'
import Image from 'next/image'
import ContentSection from '../components/ContentSection'

const SunInfinity = () => {
  const [sections, setSections] = useState(null)
  const [isLoading, setLoading] = useState(false)

  useEffect(() => {
    setLoading(true)
    fetch('api/sun-infinity')
      .then((res) => res.json())
      .then((data) => {
        setSections(data.sections)
        setLoading(false)
      })
  }, [])

  return (
    <div>
      <Head>
        <title>Sun Infinity - Pattraco</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main>
        {/* Hero Section */}
        <div className="flex">
          <div className="relative h-60 md:main-height-without-footer w-full">
            <Image
              src={solarBg}
              layout="fill"
              objectFit="cover"
              className="group-hover:scale-110 ease-in-out transform transition duration-500"
              alt="Solar Infinity"
              placeholder="blur"
            />
            <div
              className="bg-gradient-to-l 
              from-black/50 
              to-black/5
                w-full 
                h-full 
                py-6 
                text-right
                content-end 
                cursor-pointer 
                absolute 
                top-0 
                right-0 
                px-10 
                flex
                flex-col 
                justify-center 
                text-gray-100 
                z-30 
                font-extralight"
            />
            <div className="absolute z-40 w-full md:w-fit left-0 md:left-auto flex md:flex-col items-center md:items-end bottom-0 md:bottom-0 md:right-0 bg-white bg-opacity-60 text-gray-800 md:rounded-tl-xl px-4 md:text-right">
              <div className="hidden md:flex text-3xl md:text-7xl md:mb-2 font-bold">
                Sun Infinity
              </div>
              <div className="hidden md:flex text-3xl md:text-5xl font-light">
                Solar
              </div>
              <div className="text-3xl font-sans md:hidden font-light">
                Sun Infinity - Solar
              </div>
            </div>
          </div>
        </div>
        {/* Content Section */}
        {!isLoading &&
          sections &&
          sections.map((section) => (
            <ContentSection
              key={section.id}
              mainTitle={section.mainTitle}
              content={section.content}
            />
          ))}
        {/* Empty Space */}
        <div className="py-24"></div>
      </main>
    </div>
  )
}

export default SunInfinity
