import Head from 'next/head'
import { useEffect, useState } from 'react'
import ContentSectionCard from '../components/ContentSectionCard'
import HeroSection from '../components/HeroSection'
import PaddingLayout from '../components/PaddingLayout'
import csrBg from '../public/csr.webp'

const YourSoulTribe = () => {
  const [sections, setSections] = useState(null)
  const [isLoading, setLoading] = useState(false)

  useEffect(() => {
    setLoading(true)
    fetch('api/your-soul-tribe')
      .then((res) => res.json())
      .then((data) => {
        setSections(data.sections)
        setLoading(false)
      })
  }, [])

  return (
    <div>
      <Head>
        <title>Your Soul Tribe - Pattraco</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className="bg-gray-100">
        <HeroSection
          imageSrc={csrBg}
          mainTitle="Your Soul Tribe"
          subTitle="CSR"
        />
        <div className="py-6 md:py-10 bg-white">
          <div className="container mx-auto bg-white text-xl md:text-2xl md:text-center font-normal px-2 md:px-0">
            Giving back to the society is what we strive for.
          </div>
        </div>
        <div className="flex justify-center">
          <div className="grid grid-cols-1 pt-10 w-full max-w-5xl">
            {!isLoading &&
              sections &&
              sections.map((section) => (
                <ContentSectionCard
                  key={section.id}
                  mainTitle={section.mainTitle}
                  content={section.content}
                />
              ))}
          </div>
        </div>
        <PaddingLayout />
      </main>
    </div>
  )
}

export default YourSoulTribe
